pipeline:

  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount: [ /drone/.m2, /drone/.sbt ]
    volumes:
      - /tmp/cache:/cache

  build:
    image: hseeberger/scala-sbt
    environment:
      - M2_HOME=/drone/.m2
      - MAVEN_HOME=/drone/.m2
      - SBT_HOME=/drone/.sbt
    commands:
      - sbt test
      - sbt dist
      - unzip target/universal/heimdali-api.zip
    when:
      event: [ push, tag ]

  publish:
    image: plugins/docker
    repo: jotunn/heimdali-api
    tags:
      - ${DRONE_TAG}
      - latest
    secrets: [ docker_username, docker_password ]
    when:
      event: tag

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount: [ /drone/.sbt, /drone/.m2 ]
    volumes: 
      - /tmp/cache:/cache

  notify:
    image: plugins/slack
    channel: heimdali
    username: drone
    webhook: https://hooks.slack.com/services/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
    when:
      status: [ success, failure ]
