pipeline:
  build:
    image: hseeberger/scala-sbt
    commands:
      - sbt test
    when:
      event: [ push, tag ]

  publish:
    image: plugins/docker
    repo: jotunn/heimdali-api
    tags:
      - ${DRONE_TAG}
      - latest
    secrets: [ docker_username, docker_password ]
    when:
      event: tag

  nnotifyotify:
    image: plugins/slack
    channel: heimdali
    username: drone
    webhook: https://hooks.slack.com/services/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
