pipeline:
  api:
    image: hseeberger/scala-sbt
    commands:
      - sbt test

  notify:
    image: plugins/slack
    channel: heimdali
    username: drone
    webhook: https://hooks.slack.com/services/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