pipeline:

  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount: [ /drone/.ivy, /drone/.sbt ]
    volumes:
      - /tmp/cache:/cache

  build:
    image: hseeberger/scala-sbt
      - MY_ARGS=-sbt-dir /drone/.sbt -ivy /drone/.ivy
    commands:
      - sbt $MY_ARGS test
      - sbt $MY_ARGS dist
      - unzip target/universal/heimdali-api.zip
    when:
      event: [ push, tag ]

  publish:
    image: plugins/docker
    repo: jotunn/heimdali-api
    tags:
      - ${DRONE_TAG}
      - latest
    secrets: [ docker_username, docker_password ]
    when:
      event: tag

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount: [ /drone/.sbt, /drone/.ivy ]
    volumes: 
      - /tmp/cache:/cache

  notify:
    image: plugins/slack
    channel: heimdali
    username: drone
    webhook: https://hooks.slack.com/services/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
    when:
      status: [ success, failure ]
