services:
  database:
    image: postgres
    environment:
      - POSTGRES_DB=heimdali

pipeline:

  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount: [ /drone/.ivy, /drone/.sbt ]
    volumes:
      - /tmp/cache:/cache

  build:
    image: hseeberger/scala-sbt
    environment:
      - MY_ARGS=-sbt-dir /drone/.sbt -ivy /drone/.ivy
    commands:
      - sbt $MY_ARGS test
      - sbt $MY_ARGS dist
      - unzip target/universal/heimdali-api.zip

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount: [ /drone/.sbt, /drone/.ivy ]
    volumes:
      - /tmp/cache:/cache

  publish:
    image: plugins/docker
    repo: jotunn/heimdali-api
    tags:
      - "${DRONE_COMMIT_SHA:0:5}"
      - latest
    secrets: [ docker_username, docker_password ]

  deploy:
    image: quay.io/honestbee/drone-kubernetes
    deployment: heimdali-api
    namespace: heimdali
    repo: jotunn/heimdali-api
    container: heimdali-api
    secrets: [ kubernetes_server, kubernetes_cert, kubernetes_token ]
    tag:
      - "${DRONE_COMMIT_SHA:0:5}"

  notify:
    image: plugins/slack
    channel: heimdali
    username: drone
    webhook: https://hooks.slack.com/services/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
    when:
      status: [ success, failure ]
