variables:
  POSTGRES_DB: heimdali
  LDAP_DOMAIN: jotunn.io
  LDAP_READONLY: "true"
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION

cache:
  paths:
    - /root/.ivy
    - /root/.sbt

stages:
  - package
  - publish
  - notify

package:
  services:
    - postgres:9
    - name: registry.gitlab.com/jotunnllc/heimdali/heimdali-api/openldap
      alias: ldap
  stage: package
  image: openjdk:8-jdk
  script:
    - './flyway/flyway migrate -url="jdbc:postgresql://postgres:5432/heimdali" -user=postgres -password=postgres'
    - ./sbt assembly
  artifacts:
    paths:
      - target/scala-2.12/heimdali-api.jar

publish:
  stage: publish
  image: garland/aws-cli-docker
  dependencies:
    - package
  script:
    - "aws s3 mv target/scala-2.12/heimdali-api.jar s3://heimdali-repo"
  
successful_build:
  image: appropriate/curl
  stage: notify
  script: 'curl -X POST --data-urlencode "payload={\"channel\": \"#heimdali-builds\", \"username\": \"Heimdali Builder\", \"text\": \"Heimdali API -$CI_PIPELINE_URL build $CI_PIPELINE_IID Succeeded\"}" https://hooks.slack.com/services/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'
  when: on_success
  
failed_build:
  image: appropriate/curl
  stage: notify
  script: 'curl -X POST --data-urlencode "payload={\"channel\": \"#heimdali-builds\", \"username\": \"Heimdali Builder\", \"text\": \"Heimdali API -$CI_PIPELINE_URL build $CI_PIPELINE_IID Failed\"}" https://hooks.slack.com/services/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'
  when: on_failure
