image: node:alpine

stages:
  - build
  - publish
  - notify

build:
  stage: build
  artifacts:
    untracked: true
  cache:
    paths:
      - node_modules
  script:
    - npm i
    - npm run-script build

publish:
  stage: publish
  dependencies:
    - build
  artifacts:
    paths:
      - heimdali-ui.tar
    expire_in: 1 week
  script:
    - tar cvf heimdali-ui.tar build

successful_build:
  image: appropriate/curl
  stage: notify
  script: 'curl -X POST --data-urlencode "payload={\"channel\": \"#heimdali-builds\", \"username\": \"Heimdali Builder\", \"text\": \"Heimdali UI -$CI_PIPELINE_URL build $CI_PIPELINE_IID Succeeded\"}" https://hooks.slack.com/services/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'
  when: on_success

failed_build:
  image: appropriate/curl
  stage: notify
  script: 'curl -X POST --data-urlencode "payload={\"channel\": \"#heimdali-builds\", \"username\": \"Heimdali Builder\", \"text\": \"Heimdali UI -$CI_PIPELINE_URL build $CI_PIPELINE_IID Failed\"}" https://hooks.slack.com/services/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'
  when: on_failure
