stages:
  - package

package:
  stage: package
  image: java:8-jdk
  only:
    - tags
  script:
    - sed -i -e "s/0.1.0/${CI_COMMIT_TAG}/g" descriptor/service.sdl
    - jar cvf HEIMDALI-${CI_COMMIT_TAG}.jar `find . -mindepth 1 -not -path "./.git*"`
    - scp -o StrictHostKeyChecking=no -i /srv/gitlab-runner/ssh/id_rsa HEIMDALI-${CI_COMMIT_TAG}.jar ci@10.138.252.110:/srv/ci/csd/
