stages:
  - package

package:
  stage: package
  only:
    - tags
  script:
    - sed -i -e "s/0.1.0/${CI_COMMIT_TAG}/g" descriptor/service.sdl
    - jar cvf HEIMDALI-${CI_COMMIT_TAG}.jar `find . -mindepth 1 -not -path "./.git*"`
