stages:
  - package
  - notify

package:
  stage: package
  image: java:8-jdk
  only:
    - tags
  script:
    - mkdir build
    - cp -R meta build/
    - sed -i "s/0.1.5/${CI_COMMIT_TAG}/g" build/meta/parcel.json
    - java -jar /usr/src/validator.jar -p meta/parcel.json
    - java -jar /usr/src/validator.jar -r meta/permissions.json
    - mkdir -p build/usr/lib/heimdali-api
    - chown -R 10000:10000 build
    - mv build HEIMDALI-${CI_COMMIT_TAG}
    - tar cvf HEIMDALI-${CI_COMMIT_TAG}-el7.parcel HEIMDALI-${CI_COMMIT_TAG}

successful_build:
  image: appropriate/curl
  stage: notify
  script: 'curl -X POST --data-urlencode "payload={\"channel\": \"#heimdali-builds\", \"username\": \"Heimdali Builder\", \"text\": \"Heimdali CSD -$CI_PIPELINE_URL build $CI_PIPELINE_IID Succeeded\"}" https://hooks.slack.com/services/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'
  when: on_success

failed_build:
  image: appropriate/curl
  stage: notify
  script: 'curl -X POST --data-urlencode "payload={\"channel\": \"#heimdali-builds\", \"username\": \"Heimdali Builder\", \"text\": \"Heimdali CSD -$CI_PIPELINE_URL build $CI_PIPELINE_IID Failed\"}" https://hooks.slack.com/services/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'
  when: on_failure
