image: java:8-jdk

variables:
  API_TOKEN: 2CVydF3qPzVXwxL15bnq

stages:
  - build
  - publish
  - notify

build_ui:
  stage: build
  image: registry.gitlab.com/finestructure/pipeline-trigger
  only:
    - tags
  script:
    - trigger -a $API_TOKEN -p 368a051ccbbf7ddb7e6b972f347947 -e VERSION_NUMBER=$CI_COMMIT_TAG -t master 6757312

build_api:
  stage: build
  image: registry.gitlab.com/finestructure/pipeline-trigger
  only:
    - tags
  script:
    - trigger -a $API_TOKEN -p a04baacc17aabcbcb8353c3c448def -e VERSION_NUMBER=$CI_COMMIT_TAG -t master 6757317

build_self:
  stage: build
  image: registry.gitlab.com/jotunnllc/heimdali/heimdali-csd/cm-validator
  artifacts:
    untracked: true
  script:
    - java -jar /usr/src/validator.jar -p $PWD/meta/parcel.json
    - java -jar /usr/src/validator.jar -r $PWD/meta/permissions.json

publish:
  stage: publish
  dependencies:
    - build_self
  only:
    - tags
  image: registry.gitlab.com/jotunnllc/heimdali/heimdali-parcel/heimdali-deployer
  script:
    - mkdir ready
    - cp -R meta ready/
    - sed -i "s/0.1.5/${CI_COMMIT_TAG}/g" ready/meta/parcel.json
    - curl --header "PRIVATE-TOKEN: ${API_TOKEN}" -L -o ui-artifacts.zip "https://gitlab.com/api/v4/projects/6757312/jobs/artifacts/master/download?job=publish"
    - unzip ui-artifacts.zip
    - curl --header "PRIVATE-TOKEN: ${API_TOKEN}" -L -o api-artifacts.zip "https://gitlab.com/api/v4/projects/6757317/jobs/artifacts/master/download?job=publish"
    - unzip api-artifacts.zip
    - mkdir -p ready/usr/lib/heimdali-api
    - mv target/scala-2.12/heimdali-api.jar ready/usr/lib/heimdali-api/heimdali-api.jar
    - tar xvf heimdali-ui.tar
    - mv dist ready/usr/lib/heimdali-ui
    - chown -R 10000:10000 ready
    - mv ready HEIMDALI-${CI_COMMIT_TAG}
    - tar cvf HEIMDALI-${CI_COMMIT_TAG}-el7.parcel HEIMDALI-${CI_COMMIT_TAG}
    - scp -i /root/.ssh/id_rsa -o StrictHostKeyChecking=no HEIMDALI-${CI_COMMIT_TAG}-el7.parcel ci@167.99.175.193:/srv/ci/parcels/
    - ssh -i /root/.ssh/id_rsa -o StrictHostKeyChecking=no ci@167.99.175.193 "ln -s /srv/ci/parcels/HEIMDALI-${CI_COMMIT_TAG}-el7.parcel /srv/ci/parcels/HEIMDALI-${CI_COMMIT_TAG}-xenial.parcel"
    - ssh -i /root/.ssh/id_rsa -o StrictHostKeyChecking=no ci@167.99.175.193 "/srv/ci/cm_manifest/make_manifest/make_manifest.py /srv/ci/parcels/"

successful_tagged_build:
  image: appropriate/curl
  stage: notify
  script: 
    - 'curl -X POST --data-urlencode "payload={\"channel\":\"#heimdali-builds\",\"username\":\"Heimdali Parcel\",\"text\":\"Build <$CI_PIPELINE_URL|$CI_PIPELINE_IID> Succeeded\",\"attachments\":[{\"color\":\"good\",\"title\":\"Commit Message\",\"text\":\"$CI_COMMIT_TITLE\"},{\"color\":\"good\",\"title\":\"Version $CI_COMMIT_TAG Ready\",\"text\":\"http://parcels.jotunn.io\"}]}" https://hooks.slack.com/services/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'
    - 'curl -X POST --data-urlencode "payload={\"channel\":\"#heimdali-builds\",\"username\":\"Heimdali Parcel\",\"text\":\"Build <$CI_PIPELINE_URL|$CI_PIPELINE_IID> Succeeded\",\"attachments\":[{\"color\":\"good\",\"title\":\"Commit Message\",\"text\":\"$CI_COMMIT_TITLE\"},{\"color\":\"good\",\"title\":\"Version $CI_COMMIT_TAG Ready\",\"text\":\"http://parcels.jotunn.io\"}]}" https://hooks.slack.com/services/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'
  when: on_success
  only:
    variables:
      - $CI_COMMIT_TAG

successful_build:
  image: appropriate/curl
  stage: notify
  script: 'curl -X POST --data-urlencode "payload={\"channel\":\"#heimdali-builds\",\"username\":\"Heimdali Parcel\",\"text\":\"Build <$CI_PIPELINE_URL|$CI_PIPELINE_IID> Succeeded\",\"attachments\":[{\"color\":\"good\",\"title\":\"Commit Message\",\"text\":\"$CI_COMMIT_TITLE\"}]}" https://hooks.slack.com/services/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'
  when: on_success
  except:
    variables:
      - $CI_COMMIT_TAG

failed_build:
  image: appropriate/curl
  stage: notify
  script: 'curl -X POST --data-urlencode "payload={\"channel\":\"#heimdali-builds\",\"username\":\"Heimdali Parcel\",\"text\":\"Build <$CI_PIPELINE_URL|$CI_PIPELINE_IID> Failed\",\"attachments\":[{\"color\":\"danger\",\"title\":\"Commit Message\",\"text\":\"$CI_COMMIT_TITLE\"}]}" https://hooks.slack.com/services/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'
  when: on_failure
