variables:
  POSTGRES_DB: heimdali
  LDAP_DOMAIN: jotunn.io
  LDAP_READONLY: "true"
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION

stages:
  - package

package:
  services:
    - postgres:9
    - name: registry.gitlab.com/jotunnllc/heimdali/heimdali-api/openldap
      alias: ldap
  stage: package
  image: openjdk:8-jdk
  cache:
    paths:
      - /root/.ivy
      - /root/.sbt
  script:
    - './flyway/flyway migrate -url="jdbc:postgresql://postgres:5432/heimdali" -user=postgres -password=postgres'
    - ./sbt assembly
    - scp -i /srv/gitlab-runner/ssh/id_rsa target/scala-2.12/heimdali-api.jar ci@10.138.252.110:/srv/ci/builds/heimdali-api-${CI_COMMIT_TAG}.jar
  
successful_build:
  image: appropriate/curl
  stage: notify
  script: 'curl -X POST --data-urlencode "payload={\"channel\": \"#heimdali-builds\", \"username\": \"Heimdali Builder\", \"text\": \"Heimdali API -$CI_PIPELINE_URL build $CI_PIPELINE_IID Succeeded\"}" https://hooks.slack.com/services/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'
  when: on_success
  
failed_build:
  image: appropriate/curl
  stage: notify
  script: 'curl -X POST --data-urlencode "payload={\"channel\": \"#heimdali-builds\", \"username\": \"Heimdali Builder\", \"text\": \"Heimdali API -$CI_PIPELINE_URL build $CI_PIPELINE_IID Failed\"}" https://hooks.slack.com/services/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'
  when: on_failure
