stages:
  - package
  - notifyadd

package:
  stage: package
  image: java:8-jdk
  only:
    - tags
  script:
    - sed -i -e "s/0.1.0/${CI_COMMIT_TAG}/g" descriptor/service.sdl
    - jar cvf HEIMDALI-${CI_COMMIT_TAG}.jar `find . -mindepth 1 -not -path "./.git*"`
    - scp -o StrictHostKeyChecking=no -i /srv/gitlab-runner/ssh/id_rsa HEIMDALI-${CI_COMMIT_TAG}.jar ci@10.138.252.110:/srv/ci/csd/

successful_build:
  image: appropriate/curl
  stage: notify
  script: 'curl -X POST --data-urlencode "payload={\"channel\": \"#heimdali-builds\", \"username\": \"Heimdali Builder\", \"text\": \"Heimdali CSD -$CI_PIPELINE_URL build $CI_PIPELINE_IID Succeeded\"}" https://hooks.slack.com/services/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'
  when: on_success

failed_build:
  image: appropriate/curl
  stage: notify
  script: 'curl -X POST --data-urlencode "payload={\"channel\": \"#heimdali-builds\", \"username\": \"Heimdali Builder\", \"text\": \"Heimdali CSD -$CI_PIPELINE_URL build $CI_PIPELINE_IID Failed\"}" https://hooks.slack.com/services/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'
  when: on_failure
