image: java:8-jdk

stages:
  - build
  - publish
  - notify

build_ui:
  stage: build
  image: registry.gitlab.com/finestructure/pipeline-trigger
  only:
    - tags
  script:
    - trigger -a 2CVydF3qPzVXwxL15bnq -p 368a051ccbbf7ddb7e6b972f347947 -e VERSION_NUMBER=$CI_COMMIT_TAG -t master 6757312

build_api:
  stage: build
  image: registry.gitlab.com/finestructure/pipeline-trigger
  only:
    - tags
  script:
    - trigger -a 2CVydF3qPzVXwxL15bnq -p a04baacc17aabcbcb8353c3c448def -e VERSION_NUMBER=$CI_COMMIT_TAG -t master 6757317

build_self:
  stage: build
  image: registry.gitlab.com/jotunnllc/heimdali/heimdali-csd/cm-validator
  artifacts:
    untracked: true
  script:
    - java -jar /usr/src/validator.jar -p $PWD/meta/parcel.json
    - java -jar /usr/src/validator.jar -r $PWD/meta/permissions.json

publish:
  stage: publish
  dependencies:
    - build_self
  only:
    - tags
  script:
    - mkdir build
    - cp -R meta build/
    - sed -i "s/0.1.5/${CI_COMMIT_TAG}/g" build/meta/parcel.json
    - scp -o StrictHostKeyChecking=no -i /srv/gitlab-runner/ssh/id_rsa ci@10.138.252.110:/srv/ci/builds/api/heimdali-api-${CI_COMMIT_TAG}.jar heimdali-api.jar
    - scp -o StrictHostKeyChecking=no -i /srv/gitlab-runner/ssh/id_rsa ci@10.138.252.110:/srv/ci/builds/ui/heimdali-ui-${CI_COMMIT_TAG}.tar heimdali-ui.tar
    - mkdir -p build/usr/lib/heimdali-api
    - mv heimdali-api.jar build/usr/lib/heimdali-api/heimdali-api.jar
    - tar xvf heimdali-ui.tar
    - mv build build/usr/lib/heimdali-ui
    - chown -R 10000:10000 build
    - mv build HEIMDALI-${CI_COMMIT_TAG}
    - tar cvf HEIMDALI-${CI_COMMIT_TAG}-el7.parcel HEIMDALI-${CI_COMMIT_TAG}
    - scp -o StrictHostKeyChecking=no -i /srv/gitlab-runner/ssh/id_rsa HEIMDALI-${CI_COMMIT_TAG}-el7.parcel ci@10.138.252.110:/srv/ci/parcels/

successful_build:
  stage: notify
  script: 'curl -X POST --data-urlencode "payload={\"channel\": \"#heimdali-builds\", \"username\": \"Heimdali Builder\", \"text\": \"Heimdali Parcel -$CI_PIPELINE_URL build $CI_PIPELINE_IID Succeeded\"}" https://hooks.slack.com/services/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'
  when: on_success

failed_build:
  stage: notify
  script: 'curl -X POST --data-urlencode "payload={\"channel\": \"#heimdali-builds\", \"username\": \"Heimdali Builder\", \"text\": \"Heimdali Parcel -$CI_PIPELINE_URL build $CI_PIPELINE_IID Failed\"}" https://hooks.slack.com/services/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'
  when: on_failure
