image: node:alpine

stages:
  - build
  - publish
  - notify

build:
  stage: build
  artifacts:
    untracked: true
  cache:
    paths:
      - node_modules
  script:
    - npm i
    - npm run-script build

publish:
  stage: publish
  dependencies:
    - build
  only:
    variables:
      - $VERSION_NUMBER
  artifacts:
    paths:
      - heimdali-ui.tar
    expire_in: 1 week
  script:
    - tar cvf heimdali-ui.tar build

successful_build:
  stage: notify
  image: appropriate/curl
  script: 'curl -X POST --data-urlencode "payload={\"channel\":\"#heimdali-builds\",\"username\":\"Heimdali UI\",\"text\":\"Build <$CI_PIPELINE_URL|$CI_PIPELINE_IID> Succeeded\",\"attachments\":[{\"color\":\"good\",\"title\":\"Commit Message\",\"text\":\"$CI_COMMIT_TITLE\"}]}" https://hooks.slack.com/services/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'
  when: on_success

failed_build:
  stage: notify
  image: appropriate/curl
  script: 'curl -X POST --data-urlencode "payload={\"channel\":\"#heimdali-builds\",\"username\":\"Heimdali UI\",\"text\":\"Build <$CI_PIPELINE_URL|$CI_PIPELINE_IID> Failed\",\"attachments\":[{\"color\":\"danger\",\"title\":\"Commit Message\",\"text\":\"$CI_COMMIT_TITLE\"}]}" https://hooks.slack.com/services/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'
  when: on_failure
