image: openjdk:8-jdk

variables:
  POSTGRES_DB: heimdali
  LDAP_DOMAIN: jotunn.io
  LDAP_READONLY: "true"
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION

stages:
  - package
  - publish
  - notify

package:
  stage: package
  cache:
    paths:
      - .ivy
      - .sbt
  services:
    - postgres:9
    - name: registry.gitlab.com/jotunnllc/heimdali/heimdali-api/openldap
      alias: ldap
  artifacts:
    untracked: true
  script:
    - './flyway/flyway migrate -url="jdbc:postgresql://postgres:5432/heimdali" -user=postgres -password=postgres'
    - ./sbt -ivy ./.ivy -sbt-dir ./.sbt test

publish:
  stage: publish
  dependencies:
    - package
  only:
    variables:
      - $VERSION_NUMBER
  cache:
    paths:
      - .ivy
      - .sbt
  artifacts:
    paths:
      - target/scala-2.12/heimdali-api.jar
    expire_in: 1 week
  script:
    - ./sbt -ivy ./.ivy -sbt-dir ./.sbt "set test in assembly := {}" assembly

successful_build:
  stage: notify
  script: 'curl -X POST --data-urlencode "payload={\"channel\":\"#heimdali-builds\",\"username\":\"Heimdali API\",\"text\":\"Build <$CI_PIPELINE_URL|$CI_PIPELINE_IID> Succeeded\",\"attachments\":[{\"color\":\"good\",\"title\":\"Branch\",\"text\":\"$CI_COMMIT_REF_NAME\"},{\"color\":\"good\",\"title\":\"Commit Message\",\"text\":\"$CI_COMMIT_TITLE\"}]}" https://hooks.slack.com/services/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'
  when: on_success

failed_build:
  stage: notify
  script: 'curl -X POST --data-urlencode "payload={\"channel\":\"#heimdali-builds\",\"username\":\"Heimdali API\",\"text\":\"Build <$CI_PIPELINE_URL|$CI_PIPELINE_IID> Failed\",\"attachments\":[{\"color\":\"danger\",\"title\":\"Branch\",\"text\":\"$CI_COMMIT_REF_NAME\"},{\"color\":\"danger\",\"title\":\"Commit Message\",\"text\":\"$CI_COMMIT_TITLE\"}]}" https://hooks.slack.com/services/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'
  when: on_failure
