image: openjdk:8-jdk

pipelines:
  default:
    - step:
        name: "Build and Test"
        services:
          - postgres
        caches:
          - sbt
          - ivy2
        script:
          - './flyway/flyway migrate -url="jdbc:postgresql://localhost:5432/heimdali" -user=postgres -password=postgres'
          - ./sbt test
          - ./sbt it:test

  tags:
    "*":
      - step:
          name: "Package"
          caches:
            - sbt
            - ivy2
          artifacts:
            - heimdali-api/target/scala-2.12/*
          script:
            - ./sbt "set every test in assembly := {}" assembly
      - step:
          name: "Deploy"
          script:
            - mv heimdali-api/target/scala-2.12/heimdali-api.jar heimdali-api_${BITBUCKET_TAG}.jar
            - curl -u$ARTIFACTORY_USER:$ARTIFACTORY_TOKEN -T heimdali-api_${BITBUCKET_TAG}.jar "https://repository.phdata.io/artifactory/binary-dev/com/heimdali/${BITBUCKET_TAG}/heimdali-api_${BITBUCKET_TAG}.jar"

definitions:
  services:
    postgres:
      image: postgres:9
      environment:
        POSTGRES_DB: heimdali
