pipelines:
  default:
    - step:
        image: openjdk:8-jdk
        name: "Build and Test API"
        services:
          - postgres
        caches:
          - sbt
          - ivy2
        script:
          - './flyway/flyway migrate -url="jdbc:postgresql://localhost:5432/heimdali" -user=postgres -password=postgres'
          - ./sbt test
          - ./sbt it:test
    - step:
        image: node:9
        name: "Build and Test UI"
        caches:
          - node
        script:
          - npm i -g typescript
          - npm i
          - npm run-script prepare

  tags:
    "*":
      - step:
          image: openjdk:8-jdk
          name: "Package API"
          caches:
            - sbt
            - ivy2
          artifacts:
            - api/target/scala-2.12/*
          script:
            - ./sbt "set every test in assembly := {}" api/assembly
      - step:
          name: "Package API"
          image: node:9
          caches:
            - node
          artifacts:
            - dist/**
          script:
            - npm i -g typescript
            - npm i
            - npm run-script prepare
      - step:
        image: openjdk:8-jdk
          name: "Deploy"
          script:
            - mv api/target/scala-2.12/heimdali-api.jar heimdali-api_${BITBUCKET_TAG}.jar
            - curl -u$ARTIFACTORY_USER:$ARTIFACTORY_TOKEN -T heimdali-api_${BITBUCKET_TAG}.jar "https://repository.phdata.io/artifactory/binary-dev/com/heimdali/${BITBUCKET_TAG}/heimdali-api_${BITBUCKET_TAG}.jar"
            - tar cvf heimdali-ui_${BITBUCKET_TAG}.tar dist
            - curl -u$ARTIFACTORY_USER:$ARTIFACTORY_TOKEN -T heimdali-ui_${BITBUCKET_TAG}.tar "https://repository.phdata.io/artifactory/binary-dev/com/heimdali/${BITBUCKET_TAG}/heimdali-ui_${BITBUCKET_TAG}.tar"

definitions:
  services:
    postgres:
      image: postgres:9
      environment:
        POSTGRES_DB: heimdali
