image: jotunn/cm-validator

pipelines:
  default:
    - step:
        script:
          - java -jar /usr/src/validator.jar -p $PWD/meta/parcel.json
          - java -jar /usr/src/validator.jar -r $PWD/meta/permissions.json

  tags:
    "*":
      - step:
          name: "Package"
          script:
            - ./publish.sh heimdali
            - ./publish.sh custom-pioneer