image: jotunn/cm-validator

pipelines:
  default:
    - step:
        script:
          - java -jar /usr/src/validator.jar -p $PWD/heimdali-meta/parcel.json
          - java -jar /usr/src/validator.jar -r $PWD/heimdali-meta/permissions.json
          - java -jar /usr/src/validator.jar -p $PWD/custom-pioneer-meta/parcel.json

  tags:
    "*":
      - step:
          name: "Package"
          script:
            - ./publish.sh prepare heimdali
            - ./publish.sh prepare custom-pioneer
            - ./publish.sh ship