kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-pv
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-01578f0f69b2063b3
    fsType: ext4