kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-pv
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0adaabe27e0e0006a
    fsType: ext4