apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: jenkins
  name: jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - image: jenkinsci/blueocean:latest
        name: jenkins
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-volume
      securityContext:
        fsGroup: 1000
      volumes:
      - name: jenkins-volume
        awsElasticBlockStore:
          volumeID: vol-0adaabe27e0e0006a
          fsType: ext4