apiVersion: v1
kind: Service
metadata:
  name: kerberos
spec:
  ports:
  - port: 88
    protocol: TCP
    name: kdctcp
  - port: 464
    protocol: TCP
    name: pwtcp
  - port: 749
    protocol: TCP
    name: admin
  selector:
    app: kerberos
  type: LoadBalancer
