apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kerberos
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kerberos
    spec:
      containers:
      - image: jotunn/kerberos-kdc
        name: kerberos
        command:
        - "/usr/bin/kdc_init.sh"
        args:
        - "/bin/bash"
        - "-c"
        - "krb5kdc -n & kadmind -nofork"
        ports:
        - containerPort: 464
        - containerPort: 88
        - containerPort: 749
        env:
        - name: LDAP_BASE_DN
          value: "dc=jotunn,dc=io"
        - name: LDAP_BIND_DN
          valueFrom:
            secretKeyRef:
              name: ldap-creds
              key: username
        - name: LDAP_BIND_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ldap-creds
              key: password
        - name: LDAP_CRED_KEY
          valueFrom:
            secretKeyRef:
              name: ldap-creds
              key: key
      imagePullSecrets:
      - name: myregistrykey
