version: '3'
services:
  ldap:
    image: osixia/openldap
    environment:
      LDAP_DOMAIN: jotunn.io
      LDAP_READONLY_USER: "true"
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom
    command: "--loglevel debug --copy-service"