version: '2'

services:
  drone-server:
    image: drone/drone:0.7
    ports:
      - 80:8000
    volumes:
      - /var/lib/drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=http://45.76.24.152
      - DRONE_GITHUB=true
      - DRONE_GITHUB_CLIENT=8774f3109dfdc99853a6
      - DRONE_GITHUB_SECRET=d8082067de6e098afdfdc556fee45bf591f53d38
      - DRONE_SECRET=JotunnHeimdali

  drone-agent:
    image: drone/drone:0.7
    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=ws://drone-server:8000/ws/broker
      - DRONE_SECRET=JotunnHeimdali