image: jotunn/cm-validator

pipelines:
  default:
    - step:
        name: "Validate"
        script:
          - java -jar /usr/src/validator.jar -s $PWD/descriptor/service.sdl

  tags:
    "*":
      - step:
          name: "Package and deploy"
          script:
            - sed -i -e "s/0.1.0/${BITBUCKET_TAG}/g" descriptor/service.sdl
            - jar cvf HEIMDALI-${BITBUCKET_TAG}.jar `find . -mindepth 1 -not -path "./.git*"`
            - curl -u$ARTIFACTORY_USER:$ARTIFACTORY_TOKEN -T HEIMDALI-${BITBUCKET_TAG}.jar https://repository.phdata.io/artifactory/parcels-release/com/heimdali/${BITBUCKET_TAG}/HEIMDALI-${BITBUCKET_TAG}.jar